### ISSUE TITLE
Why use Docker?

### ISSUE THREAD

**Issue by clearnote01** [paramsingh/poj#3]
I am curious as to why you have used Docker. As far I can see, you are using to set up up a environment with dependencies 'gcc' and 'g++' and since these are already trivial task on linux machine, what does docker exactly achieve? 

Another query that I have is related to functioning of Docker. Since it uses Linux Kernel features, does it work on different Linux OS like Debian and Fedora in the same way considering that Fedora uses **yum** instead of **apt**?

**Comment by paramsingh** [comment]
@clearnote01 I'm using docker to make sure that code like `system("rm -rf /bin")` doesn't kill the server. Docker creates a new container which has all the stuff installed for every submission. So if malicious code is run on the container, it will only get access to the container and not the server (ideally).

Also, the poj image is based on the [ubuntu14.04 image](https://hub.docker.com/r/_/ubuntu/) on docker hub so if you build the image using the Dockerfile in the repo, it should work on any linux distribution supported by Docker because the image is an ubuntu one.
